
spring:
  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /WEB-INF/board/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          #show_sql: true
          format_sql: true

  h2:
    console:
      enabled: true

  profiles:
    include: prod


logging:
  level:
    org:
      hibernate : INFO
      springframework:
        security : DEBUG
